// src/ui/react/components/workspace/WorkspaceGrid.jsx
// Clean instance creation flow with proper ID handling

import React, { useState, useEffect, useRef, useCallback } from "react";
import { Plus, Users, X } from "lucide-react";
import { instanceManager } from "@Core/instances/instanceManager.js";
import { InstanceViewport } from "@UI/react/components/workspace/InstanceViewport.jsx";
import { RemoteInstancePlaceholder } from "@UI/react/components/workspace/RemoteInstancePlaceholder.jsx";

export function WorkspaceGrid() {
    // Track instances to render
    // Structure: { key, datasetId, isRemote, remoteId, userName }
    const [instances, setInstances] = useState([]);

    // Pending remote instances
    const [pendingRemoteInstances, setPendingRemoteInstances] = useState([]);
    const [showNotification, setShowNotification] = useState(false);

    const gridRef = useRef(null);
    const initialized = useRef(false);

    /**
     * Initialize instance manager
     */
    useEffect(() => {
        if (!initialized.current) {
            initialized.current = true;
            console.log("🎨 WorkspaceGrid: Initializing...");

            // Initialize the instance manager
            instanceManager.initialize();

            // Listen for remote instance changes
            const cleanup = instanceManager.onRemoteInstanceChange((event) => {
                console.log('📬 WorkspaceGrid: Received remote instance event:', event.action);

                if (event.action === "add") {
                    console.log(`   Instance: ${event.instanceId}`);
                    console.log(`   From: ${event.instance.userName}`);

                    // Add to pending
                    setPendingRemoteInstances((prev) => {
                        const newPending = [...prev, {
                            instanceId: event.instanceId,
                            userName: event.instance.userName,
                            datasetId: event.instance.datasetId,
                        }];
                        console.log(`   Total pending: ${newPending.length}`);
                        return newPending;
                    });
                    setShowNotification(true);
                }

                if (event.action === "delete") {
                    setInstances((prev) =>
                        prev.filter((i) => i.remoteId !== event.instanceId)
                    );
                    setPendingRemoteInstances((prev) =>
                        prev.filter((p) => p.instanceId !== event.instanceId)
                    );
                }
            });

            // NEW: Check for existing remote instances after callback is registered
            // This handles instances that were created before we connected
            setTimeout(() => {
                const yInstances = window.CIA?.yInstances;
                const getUserId = window.CIA?.getUserId;

                if (yInstances && getUserId) {
                    const currentUserId = getUserId();
                    const existingRemote = [];

                    yInstances.forEach((instance, instanceId) => {
                        if (instance.userId !== currentUserId && instance.visibility === 'shared') {
                            console.log(`📬 WorkspaceGrid: Found existing remote instance: ${instanceId}`);
                            existingRemote.push({
                                instanceId,
                                userName: instance.userName,
                                datasetId: instance.datasetId,
                            });
                        }
                    });

                    if (existingRemote.length > 0) {
                        console.log(`   Found ${existingRemote.length} existing remote instances`);
                        setPendingRemoteInstances(existingRemote);
                        setShowNotification(true);
                    }
                }
            }, 100);

            console.log("✅ WorkspaceGrid initialized");
            return cleanup;
        }
    }, []);

    /**
     * Listen for dataset selection from FilesPanel
     */
    useEffect(() => {
        const handleInstanceRequest = (event) => {
            const datasetId = event.detail?.datasetId;

            if (!datasetId || typeof datasetId !== 'string') {
                console.error('❌ Invalid dataset ID:', datasetId);
                return;
            }

            console.log('📬 Creating instance for dataset:', datasetId);

            // Add to instances list
            // Use timestamp as unique key for React
            // The actual instance ID will be generated by instanceManager
            setInstances((prev) => [...prev, {
                key: `local-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
                datasetId: datasetId,
                isRemote: false,
            }]);
        };

        window.addEventListener('cia:request-instance', handleInstanceRequest);
        return () => {
            window.removeEventListener('cia:request-instance', handleInstanceRequest);
        };
    }, []);

    /**
     * Create empty instance
     */
    const handleCreateEmptyInstance = useCallback(() => {
        console.log('➕ Creating empty instance');

        setInstances((prev) => [...prev, {
            key: `local-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
            datasetId: null,
            isRemote: false,
        }]);
    }, []);

    /**
     * Accept remote instances
     */
    const handleAcceptRemoteInstances = useCallback(() => {
        console.log(`✅ Accepting ${pendingRemoteInstances.length} remote instances`);

        pendingRemoteInstances.forEach((remote) => {
            setInstances((prev) => [...prev, {
                key: `remote-${remote.instanceId}`,
                datasetId: remote.datasetId,
                isRemote: true,
                remoteId: remote.instanceId,  // The actual instance ID from Y.js
                userName: remote.userName,
            }]);
        });

        setPendingRemoteInstances([]);
        setShowNotification(false);
    }, [pendingRemoteInstances]);

    /**
     * Dismiss notification
     */
    const handleDismissNotification = useCallback(() => {
        setPendingRemoteInstances([]);
        setShowNotification(false);
    }, []);

    /**
     * Delete instance
     */
    const handleDeleteInstance = useCallback((key) => {
        console.log(`🗑️ Removing instance from grid: ${key}`);
        setInstances((prev) => prev.filter((i) => i.key !== key));
    }, []);

    /**
     * Calculate grid layout
     */
    const getGridStyle = () => {
        const count = instances.length;

        if (count === 0) {
            return { display: "none" };
        }

        let cols = 1;
        let rows = 1;

        if (count === 1) {
            cols = 1; rows = 1;
        } else if (count === 2) {
            cols = 2; rows = 1;
        } else if (count <= 4) {
            cols = 2; rows = 2;
        } else if (count <= 6) {
            cols = 3; rows = 2;
        } else {
            cols = 3; rows = 3;
        }

        return {
            display: "grid",
            gridTemplateColumns: `repeat(${cols}, 1fr)`,
            gridTemplateRows: `repeat(${rows}, 1fr)`,
            gap: "12px",
            padding: "12px",
            height: "100%",
            overflow: "auto",
        };
    };

    return (
        <div style={{ display: "flex", flexDirection: "column", height: "100%", position: "relative" }}>

            {/* Remote Instance Notification */}
            {showNotification && pendingRemoteInstances.length > 0 && (
                <div style={{
                    position: "absolute",
                    top: "20px",
                    left: "50%",
                    transform: "translateX(-50%)",
                    zIndex: 1000,
                    minWidth: "400px",
                    background: "linear-gradient(135deg, #1a1a1a 0%, #2a2a2a 100%)",
                    border: "2px solid #4CAF50",
                    borderRadius: "12px",
                    padding: "20px",
                    boxShadow: "0 8px 24px rgba(0, 0, 0, 0.6)",
                    animation: "slideDown 0.3s ease-out",
                }}>
                    <div style={{
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "space-between",
                        marginBottom: "12px",
                    }}>
                        <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                            <Users size={20} color="#4CAF50" />
                            <h3 style={{ margin: 0, fontSize: "16px", color: "#fff" }}>
                                Shared Views Available
                            </h3>
                        </div>
                        <button
                            onClick={handleDismissNotification}
                            style={{
                                background: "transparent",
                                border: "none",
                                color: "#999",
                                cursor: "pointer",
                                padding: "4px",
                            }}
                        >
                            <X size={18} />
                        </button>
                    </div>

                    <div style={{ marginBottom: "16px", color: "#ccc", fontSize: "14px" }}>
                        {pendingRemoteInstances.map((remote, idx) => (
                            <div key={idx} style={{ marginBottom: "4px" }}>
                                • <strong>{remote.userName}</strong> is viewing{" "}
                                {remote.datasetId ? "a dataset" : "an empty viewport"}
                            </div>
                        ))}
                    </div>

                    <div style={{ display: "flex", gap: "8px", justifyContent: "flex-end" }}>
                        <button
                            onClick={handleDismissNotification}
                            style={{
                                padding: "8px 16px",
                                background: "#3a3a3a",
                                border: "1px solid #555",
                                borderRadius: "6px",
                                color: "#fff",
                                cursor: "pointer",
                                fontSize: "14px",
                            }}
                        >
                            Dismiss
                        </button>
                        <button
                            onClick={handleAcceptRemoteInstances}
                            style={{
                                padding: "8px 16px",
                                background: "#4CAF50",
                                border: "none",
                                borderRadius: "6px",
                                color: "#fff",
                                cursor: "pointer",
                                fontSize: "14px",
                                fontWeight: 600,
                            }}
                        >
                            Open Views Now
                        </button>
                    </div>
                </div>
            )}

            {/* Toolbar */}
            <div style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                padding: "12px 16px",
                backgroundColor: "#1a1a1a",
                borderBottom: "1px solid #2a2a2a",
                flexShrink: 0,
            }}>
                <span style={{ color: "#fff", fontSize: "14px", fontWeight: 600 }}>
                    Workspace ({instances.length} instance{instances.length !== 1 ? "s" : ""})
                    {instances.filter((i) => i.isRemote).length > 0 && (
                        <span style={{ color: "#4CAF50", marginLeft: "8px", fontSize: "12px" }}>
                            ({instances.filter((i) => i.isRemote).length} remote)
                        </span>
                    )}
                    {pendingRemoteInstances.length > 0 && (
                        <span style={{
                            color: "#FFA726",
                            marginLeft: "8px",
                            fontSize: "12px",
                            animation: "pulse 2s infinite",
                        }}>
                            ({pendingRemoteInstances.length} pending)
                        </span>
                    )}
                </span>
                <button
                    onClick={handleCreateEmptyInstance}
                    disabled={instances.length >= 9}
                    style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "6px",
                        padding: "8px 14px",
                        backgroundColor: instances.length >= 9 ? "#2a2a2a" : "#3a5a3a",
                        border: "none",
                        borderRadius: "4px",
                        color: instances.length >= 9 ? "#666" : "#fff",
                        cursor: instances.length >= 9 ? "not-allowed" : "pointer",
                        fontSize: "13px",
                        fontWeight: 600,
                        transition: "all 0.2s",
                    }}
                >
                    <Plus size={16} />
                    Add Instance
                </button>
            </div>

            {/* Empty State or Grid */}
            {instances.length === 0 ? (
                <div style={{
                    flex: 1,
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center",
                    justifyContent: "center",
                    backgroundColor: "#0a0a0a",
                    color: "#666",
                    gap: "16px",
                    padding: "40px",
                }}>
                    <div style={{ fontSize: "48px", opacity: 0.3 }}>🎨</div>
                    <div style={{ fontSize: "16px", fontWeight: 600, color: "#888" }}>
                        No visualization windows open
                    </div>
                    <div style={{
                        fontSize: "13px",
                        color: "#666",
                        textAlign: "center",
                        maxWidth: "400px",
                        lineHeight: 1.5,
                    }}>
                        Click a dataset from the Files panel to create a window with that data,
                        or click "Add Instance" above to create an empty window.
                    </div>
                    <button
                        onClick={handleCreateEmptyInstance}
                        style={{
                            marginTop: "16px",
                            display: "flex",
                            alignItems: "center",
                            gap: "8px",
                            padding: "10px 20px",
                            backgroundColor: "#3a5a3a",
                            border: "none",
                            borderRadius: "6px",
                            color: "#fff",
                            cursor: "pointer",
                            fontSize: "14px",
                            fontWeight: 600,
                            transition: "all 0.2s",
                        }}
                    >
                        <Plus size={18} />
                        Create Instance
                    </button>
                </div>
            ) : (
                <div ref={gridRef} style={getGridStyle()}>
                    {instances.map((instance) => {
                        // For remote instances, check if we have the dataset
                        if (instance.isRemote && instance.datasetId) {
                            const datasetManager = window.CIA?.datasetManager;
                            const dataset = datasetManager?.getDataset(instance.datasetId);

                            if (!dataset) {
                                // We don't have this dataset yet - show placeholder
                                // Get the dataset metadata from Y.js
                                const ydoc = window.CIA?.ydoc;
                                const yDatasets = ydoc?.getMap('datasets');
                                const datasetMetadata = yDatasets?.get(instance.datasetId);

                                if (!datasetMetadata) {
                                    // No metadata available - can't create placeholder
                                    console.warn(`No metadata for dataset ${instance.datasetId}`);
                                    return null;
                                }

                                return (
                                    <RemoteInstancePlaceholder
                                        key={instance.key}
                                        instanceId={instance.remoteId}
                                        datasetId={instance.datasetId}
                                        ownerId={instance.userId}
                                        ownerName={instance.userName}
                                        datasetFilename={datasetMetadata.filename}
                                        datasetFileType={datasetMetadata.fileType}
                                        publicPath={datasetMetadata.publicPath}
                                        storageKey={datasetMetadata.storageKey}
                                        onFetchAndView={async (fetchInfo) => {
                                            try {
                                                // Fetch the dataset using instance manager
                                                await instanceManager.fetchDatasetForRemoteInstance(fetchInfo);

                                                // Force re-render by updating state
                                                // This will cause the check above to pass next render
                                                // and display an InstanceViewport instead of placeholder
                                                setInstances([...instances]);

                                            } catch (error) {
                                                console.error('Failed to fetch dataset:', error);
                                                throw error; // Let placeholder component show the error
                                            }
                                        }}
                                    />
                                );
                            }
                        }

                        // Normal case - render the instance viewport
                        return (
                            <InstanceViewport
                                key={instance.key}
                                datasetId={instance.datasetId}
                                isRemote={instance.isRemote}
                                remoteInstanceId={instance.remoteId}
                                ownerUserName={instance.userName}
                                onDelete={() => handleDeleteInstance(instance.key)}
                            />
                        );
                    })}
                </div>
            )}

            {/* Animations */}
            <style>{`
        @keyframes slideDown {
          from {
            opacity: 0;
            transform: translateX(-50%) translateY(-20px);
          }
          to {
            opacity: 1;
            transform: translateX(-50%) translateY(0);
          }
        }
        
        @keyframes pulse {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.5; }
        }
      `}</style>
        </div>
    );
}