// iconMap.js
// Icon mapping for tool components

import {
  MousePointer,
  Move,
  RotateCcw,
  ZoomIn,
  Palette,
  Circle,
  CircleDot,
  Sliders,
  Scissors,
  Grid3X3,
  Ruler,
  Compass,
  Crosshair,
  MapPin,
  Square,
  MessageSquare,
  Eye,
  EyeOff,
  Settings,
  Save,
  Monitor,
  Users,
  PenTool,
  Box,
  Plus,
  FlipHorizontal,
  Copy,
  Trash2,
  Wand2,
  Camera,
  Triangle,
  X,
  Maximize2,
  BarChart3,
  Activity,
  Network,
  Wrench,
  Layers,
  Minus,
} from 'lucide-react';

export const ICON_MAP = {
  "mouse-pointer": MousePointer,
  move: Move,
  "rotate-ccw": RotateCcw,
  "zoom-in": ZoomIn,
  palette: Palette,
  circle: Circle,
  "circle-dot": CircleDot,
  sliders: Sliders,
  scissors: Scissors,
  "grid-3x3": Grid3X3,
  ruler: Ruler,
  compass: Compass,
  crosshair: Crosshair,
  "map-pin": MapPin,
  square: Square,
  "message-square": MessageSquare,
  eye: Eye,
  "eye-off": EyeOff,
  settings: Settings,
  save: Save,
  monitor: Monitor,
  users: Users,
  "pen-tool": PenTool,
  box: Box,
  plus: Plus,
  "flip-horizontal": FlipHorizontal,
  copy: Copy,
  "trash-2": Trash2,
  "wand-2": Wand2,
  camera: Camera,
  triangle: Triangle,
  x: X,
  "maximize-2": Maximize2,
  "bar-chart-3": BarChart3,
  activity: Activity,
  network: Network,
  transform: Box,
  wrench: Wrench,
  layers: Layers,
  minus: Minus,
};

export function getIcon(iconName) {
  if (!iconName) return Box;
  return ICON_MAP[iconName] || ICON_MAP[iconName.toLowerCase()] || Box;
}
