/**
 * Thumbnail Service
 *
 * Manages server-side thumbnail generation jobs.
 * Thumbnails are generated by a headless browser worker to ensure
 * they accurately represent the visualization (no client tampering).
 */

const { Queue } = require("bullmq");
const { createLogger } = require("../utils/logger");

const log = createLogger("thumbnails");

// Redis connection config
const connection = {
  host: process.env.REDIS_HOST || "localhost",
  port: parseInt(process.env.REDIS_PORT || "6379"),
};

// Thumbnail queue
let thumbnailQueue = null;

/**
 * Get or create the thumbnail queue
 */
function getQueue() {
  if (!thumbnailQueue) {
    thumbnailQueue = new Queue("thumbnail", { connection });
    log.info("Thumbnail queue initialized");
  }
  return thumbnailQueue;
}

/**
 * Queue a thumbnail generation job for a file
 *
 * @param {object} options
 * @param {string} options.fileId - The file ID
 * @param {object} options.pool - Database pool
 * @param {string} options.viewId - Optional view configuration ID
 * @param {string} options.projectId - Optional project ID for access control
 * @param {number} options.priority - Job priority (1-10, higher = more urgent)
 * @returns {Promise<object>} - The queued job
 */
async function queueThumbnailJob({
  fileId,
  pool,
  viewId = null,
  projectId = null,
  priority = 5,
}) {
  const queue = getQueue();

  // Look up handler type from database (server-authoritative)
  let handlerType = null;
  if (pool && fileId) {
    try {
      const result = await pool.query(
        "SELECT handler_type FROM datasets WHERE id = $1",
        [fileId]
      );
      handlerType = result.rows[0]?.handler_type;
    } catch (err) {
      log.warn(
        `Could not look up handler_type for file ${fileId}:`,
        err.message
      );
    }
  }

  const jobData = {
    fileId,
    viewId: viewId || null,
    projectId: projectId || null,
    handlerType, // Server-determined handler type
    callbackUrl: `${
      process.env.API_URL || "http://localhost:3001"
    }/api/thumbnails/callback`,
    queuedAt: new Date().toISOString(),
  };

  const job = await queue.add("generate-thumbnail", jobData, {
    priority,
    attempts: 3,
    backoff: {
      type: "exponential",
      delay: 5000,
    },
    removeOnComplete: 100,
    removeOnFail: 50,
  });

  log.info(
    `Queued thumbnail job ${job.id} for file=${fileId}, view=${viewId}, type=${handlerType}`
  );

  return {
    jobId: job.id,
    fileId,
    viewId,
    handlerType,
    status: "queued",
  };
}

/**
 * Queue thumbnail jobs for all views of a file
 *
 * @param {object} pool - Database pool
 * @param {string} fileId - The file ID
 * @returns {Promise<object[]>} - Array of queued jobs
 */
async function queueThumbnailsForFile(pool, fileId) {
  // Get all active views for this file
  const result = await pool.query(
    `SELECT id FROM view_configurations
     WHERE dataset_id = $1 AND status = 'active'`,
    [fileId]
  );

  const jobs = [];
  for (const row of result.rows) {
    const job = await queueThumbnailJob({
      fileId,
      pool,
      viewId: row.id,
      priority: 3, // Lower priority for batch jobs
    });
    jobs.push(job);
  }

  // If no views exist, queue a job for the file itself
  // (will create a default view when rendered)
  if (jobs.length === 0) {
    const job = await queueThumbnailJob({ fileId, pool, priority: 5 });
    jobs.push(job);
  }

  log.info(`Queued ${jobs.length} thumbnail jobs for file ${fileId}`);
  return jobs;
}

/**
 * Handle thumbnail job completion callback
 *
 * @param {object} pool - Database pool
 * @param {object} result - Job result from worker
 */
async function handleThumbnailCallback(pool, result) {
  const { jobId, success, storageKey, format, width, height, error } = result;

  if (!success) {
    log.error(`Thumbnail job ${jobId} failed: ${error}`);
    return { success: false, error };
  }

  // Extract viewId from job data (we need to look it up or pass it in result)
  // For now, parse from storage key: thumbnails/{viewId}/thumbnail.webp
  const match = storageKey?.match(/thumbnails\/([^/]+)\//);
  const viewId = match ? match[1] : null;

  if (!viewId) {
    log.error(`Cannot determine viewId from storage key: ${storageKey}`);
    return { success: false, error: "Invalid storage key" };
  }

  // Upsert thumbnail record
  await pool.query(
    `INSERT INTO view_thumbnails (view_config_id, storage_key, format, width, height)
     VALUES ($1, $2, $3, $4, $5)
     ON CONFLICT (view_config_id, snapshot_id)
     DO UPDATE SET storage_key = $2, format = $3, width = $4, height = $5, updated_at = NOW()`,
    [viewId, storageKey, format, width, height]
  );

  log.info(`Thumbnail saved for view ${viewId}: ${storageKey}`);

  return { success: true, viewId, storageKey };
}

/**
 * Check if a thumbnail exists for a view
 *
 * @param {object} pool - Database pool
 * @param {string} viewId - View configuration ID
 * @returns {Promise<boolean>}
 */
async function hasThumbnail(pool, viewId) {
  const result = await pool.query(
    `SELECT 1 FROM view_thumbnails
     WHERE view_config_id = $1 AND snapshot_id IS NULL
     LIMIT 1`,
    [viewId]
  );
  return result.rows.length > 0;
}

module.exports = {
  queueThumbnailJob,
  queueThumbnailsForFile,
  handleThumbnailCallback,
  hasThumbnail,
  getQueue,
};
