#!/bin/bash
echo "=== Checking Docker Services ==="
echo ""
echo "Docker containers:"
docker ps -a --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" 2>/dev/null || echo "Docker not available in this environment"
echo ""
echo "Checking ports:"
echo -n "PostgreSQL (5432): "
nc -zv localhost 5432 2>&1 | grep -q "succeeded" && echo "✅ Open" || echo "❌ Closed"
echo -n "MinIO API (9000): "
nc -zv localhost 9000 2>&1 | grep -q "succeeded" && echo "✅ Open" || echo "❌ Closed"
echo -n "API Server (3001): "
nc -zv localhost 3001 2>&1 | grep -q "succeeded" && echo "✅ Open" || echo "❌ Closed"
echo -n "WebSocket (9001): "
nc -zv localhost 9001 2>&1 | grep -q "succeeded" && echo "✅ Open" || echo "❌ Closed"